# Generated by Django 5.2.1 on 2026-01-09 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycontent',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
