# Generated by Django 5.2.1 on 2026-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studycontent_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycontent',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
