# Generated by Django 5.2.1 on 2026-01-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studycontent_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycontent',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20),
        ),
    ]
