# Generated by Django 6.0.1 on 2026-01-11 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aiconversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_message_limit', models.IntegerField()),
                ('requests_per_minute', models.IntegerField()),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0.0005, max_digits=8),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='model_used',
            field=models.CharField(default='llama-3.1-8b-instant', max_length=100),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='response_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user_tier_at_time',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='was_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studycontent',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studycontent',
            name='ai_generation_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='studycontent',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='ai_assistance_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='estimated_ai_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='average_cost_per_query',
            field=models.DecimalField(decimal_places=4, default=0.001, max_digits=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_queries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messages_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requests_per_minute',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free Tier'), ('premium', 'Premium ($9.99/month)'), ('unlimited', 'Unlimited ($19.99/month)')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_api_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='Beginner', max_length=100),
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('limit_type', models.CharField(max_length=50)),
                ('limit_value', models.IntegerField()),
                ('current_usage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], max_length=20)),
                ('stripe_subscription_id', models.CharField(max_length=100)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=6, max_digits=8)),
                ('response_time_ms', models.IntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_apiusag_user_id_feaa20_idx'), models.Index(fields=['timestamp'], name='api_apiusag_timesta_137f2a_idx')],
            },
        ),
    ]
