# Generated by Django 6.0.1 on 2026-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subscriptionplan_aiconversation_cache_hit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_api_cost',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='beginner', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free Tier'), ('premium', 'Premium'), ('unlimited', 'Unlimited')], default='free', max_length=20),
        ),
    ]
