# Generated by Django 6.0.1 on 2026-01-12 00:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_last_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAutoSetupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('setup_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIProxyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_user_cost', models.DecimalField(decimal_places=6, default=0.0005, max_digits=8)),
                ('your_service_fee', models.DecimalField(decimal_places=6, default=0.0001, max_digits=8)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('pdf', 'PDF Analysis'), ('data', 'Data Analysis'), ('other', 'Other')], default='chat', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('stripe_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hosting_fee', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=6)),
                ('stripe_payment_intent_id', models.CharField(max_length=100)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_invoice_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='succeeded', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hosting_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_free_users', models.IntegerField(default=0)),
                ('active_premium_users', models.IntegerField(default=0)),
                ('active_unlimited_users', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens_proxied', models.BigIntegerField(default=0)),
                ('total_your_service_fees', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profit Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='apiusagelog',
            name='api_apiusag_user_id_feaa20_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiusagelog',
            name='api_apiusag_timesta_137f2a_idx',
        ),
        migrations.RenameField(
            model_name='aiconversation',
            old_name='estimated_cost',
            new_name='estimated_user_cost',
        ),
        migrations.RenameField(
            model_name='studycontent',
            old_name='ai_generation_cost',
            new_name='estimated_user_token_cost',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='estimated_ai_cost',
            new_name='estimated_user_token_cost',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='messages_today',
            new_name='data_analyses_this_month',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_messages',
            new_name='pdf_analyses_this_month',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='average_cost_per_query',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='daily_message_limit',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='requests_per_minute',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='requests_per_minute',
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='api_provider',
            field=models.CharField(default='openai', max_length=50),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='your_service_fee',
            field=models.DecimalField(decimal_places=6, default=0.0001, max_digits=8),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='average_tokens_per_query',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_data_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_pdf_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='suggested_daily_requests',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='suggested_monthly_tokens',
            field=models.IntegerField(default=250000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('unlimited', 'Unlimited')], default='premium', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='your_cost_per_user',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_model',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requests_this_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requests_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], default='trialing', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tokens_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='model_used',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free Tier'), ('premium', 'Premium ($19.99)'), ('unlimited', 'Unlimited ($49.99)')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiautosetuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiproxylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='apiusagelog',
            name='user',
        ),
        migrations.AddIndex(
            model_name='apiproxylog',
            index=models.Index(fields=['user', 'timestamp'], name='api_apiprox_user_id_d242c9_idx'),
        ),
        migrations.AddIndex(
            model_name='apiproxylog',
            index=models.Index(fields=['timestamp'], name='api_apiprox_timesta_bf7931_idx'),
        ),
        migrations.AddIndex(
            model_name='apiproxylog',
            index=models.Index(fields=['provider', 'timestamp'], name='api_apiprox_provide_a822df_idx'),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['user', 'timestamp'], name='api_billing_user_id_71cc62_idx'),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['status', 'timestamp'], name='api_billing_status_8ee080_idx'),
        ),
        migrations.DeleteModel(
            name='APIUsageLog',
        ),
    ]
