# Generated by Django 6.0.1 on 2026-01-12 00:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_apiautosetuprequest_apiproxylog_billingtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiautosetuprequest',
            name='free_tokens_info',
            field=models.CharField(blank=True, default='5,000,000 tokens/month', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profitanalytics',
            name='free_tokens_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profitanalytics',
            name='groq_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='FREE - 5M tokens/month at Groq.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='api_provider',
            field=models.CharField(default='groq', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='estimated_user_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='model_used',
            field=models.CharField(default='llama-3.1-8b-instant', max_length=100),
        ),
        migrations.AlterField(
            model_name='apiautosetuprequest',
            name='provider',
            field=models.CharField(choices=[('groq', '🔥 Groq (FREE)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='groq', max_length=50),
        ),
        migrations.AlterField(
            model_name='apiproxylog',
            name='estimated_user_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apiproxylog',
            name='provider',
            field=models.CharField(default='groq', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(default='Get started with FREE Groq AI!'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='your_cost_per_user',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_model',
            field=models.CharField(default='llama-3.1-8b-instant', help_text='Free models: llama-3.1-8b-instant, mixtral-8x7b-32768', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_provider',
            field=models.CharField(choices=[('groq', '🔥 Groq (FREE - 5M tokens/month)'), ('openai', 'OpenAI (Paid)'), ('anthropic', 'Anthropic (Paid)'), ('gemini', 'Google Gemini (Paid)')], default='groq', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free Tier (50 requests/day)'), ('premium', 'Premium ($19.99/month)'), ('unlimited', 'Unlimited ($49.99/month)')], default='free', max_length=20),
        ),
    ]
