# Generated by Django 6.0.1 on 2026-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profitanalytics_total_reseller_commissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openai_key_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='OpenAI credit balance if available', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_key_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('free_tier', 'Free Tier (gpt-3.5-turbo)'), ('pay_as_you_go', 'Pay-as-you-go (All models)'), ('enterprise', 'Enterprise')], default='unknown', max_length=20),
        ),
    ]
