# Generated by Django 6.0.1 on 2026-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_openai_key_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this request was FREE (Groq or free tier OpenAI)'),
        ),
    ]
