# Generated by Django 6.0.1 on 2026-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aiconversation_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groq_available_models',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of available Groq models'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_total_models_count',
            field=models.IntegerField(default=0, help_text='Total number of Groq models available'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_model_detection',
            field=models.DateTimeField(blank=True, help_text='When was model access last detected?', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_account_status',
            field=models.CharField(choices=[('active', 'Active'), ('free_credits_expired', 'Free Credits Expired'), ('low_balance', 'Low Balance'), ('inactive', 'Inactive')], default='active', help_text='Status of the OpenAI account', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_available_gpt35_models',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of available GPT-3.5 models'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_available_gpt4_models',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of available GPT-4 models'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_can_use_paid_models',
            field=models.BooleanField(default=False, help_text='Can this account use paid models?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_has_finetuning_access',
            field=models.BooleanField(default=False, help_text='Does this key have fine-tuning access?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_has_gpt4_access',
            field=models.BooleanField(default=False, help_text='Does this OpenAI key have GPT-4 access?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_has_gpt4_vision',
            field=models.BooleanField(default=False, help_text='Does this key have GPT-4 Vision access?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_has_payment_method',
            field=models.BooleanField(default=False, help_text='Does the OpenAI account have a payment method?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_recommended_model',
            field=models.CharField(default='gpt-3.5-turbo', help_text='Recommended model based on account type', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_total_models_count',
            field=models.IntegerField(default=0, help_text='Total number of models available with this key'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider_capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='JSON summary of provider capabilities (models, limits, etc.)'),
        ),
    ]
