# Generated by Django 6.0.1 on 2026-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_groq_available_models_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groq_available_models',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groq_total_models_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_model_detection',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_available_gpt35_models',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_available_gpt4_models',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_can_use_paid_models',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_has_finetuning_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_has_gpt4_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_has_gpt4_vision',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_has_payment_method',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_recommended_model',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_total_models_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='provider_capabilities',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='For GPT-3.5 Turbo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='openai_key_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('free_tier', 'Free Tier'), ('pay_as_you_go', 'Pay-as-you-go')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_model',
            field=models.CharField(choices=[('llama-3.1-8b-instant', 'Llama 3.1 8B (Instant) - FREE'), ('mixtral-8x7b-32768', 'Mixtral 8x7B - FREE'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-3.5-turbo-instruct', 'GPT-3.5 Turbo Instruct')], default='llama-3.1-8b-instant', help_text='Select model based on your provider', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_provider',
            field=models.CharField(choices=[('groq', '🔥 Groq (FREE - 5M tokens/month)'), ('openai', 'OpenAI (GPT-3.5 Turbo)')], default='groq', max_length=50),
        ),
    ]
