# Generated by Django 6.0.1 on 2026-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_userprofile_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiautosetuprequest',
            name='provider',
            field=models.CharField(choices=[('groq', '🔥 Groq (FREE)'), ('openai', 'OpenAI')], default='groq', max_length=50),
        ),
    ]
