# Generated by Django 6.0.1 on 2026-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_apiautosetuprequest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='key_source',
            field=models.CharField(choices=[('user', 'User API Key'), ('system_fallback', 'System Fallback Key')], default='user', max_length=20),
        ),
    ]
