# Generated by Django 6.0.1 on 2026-01-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_aiconversation_key_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconversation',
            name='key_source',
        ),
    ]
