# Generated by Django 6.0.1 on 2026-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_aiconversation_key_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='key_source',
            field=models.CharField(choices=[('user', 'User API Key'), ('env', 'Environment API Key (Fallback)'), ('system', 'System Fallback Key')], default='user', help_text='Source of the API key used for this request', max_length=50),
        ),
    ]
