# Generated by Django 6.0.1 on 2026-01-12 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_aiconversation_key_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('image', 'Image File'), ('excel', 'Excel File'), ('ppt', 'PowerPoint File')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_model', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_tokens', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
