# Generated by Django 6.0.1 on 2026-01-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='document_analyzed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='api.uploadeddocument'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='is_document_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiproxylog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='api.uploadeddocument'),
        ),
    ]
