# Generated by Django 6.0.1 on 2026-01-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_aiconversation_document_analyzed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='image_generation_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='is_image_generation',
            field=models.BooleanField(default=False),
        ),
    ]
