"""
Django settings for studypilot project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import dj_database_url

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n1*q3euj_7h2envk^y_pjus!zb3&tom%jyvj)8p3ip1(t0c00&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost', 
    '0.0.0.0', 
    '.up.railway.app', 
    'hadsxk-production.up.railway.app',
    'kbytexfrontend.vercel.app',
    '.vercel.app',

     'kbytex.com',
    'www.kbytex.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://hadsxk-production.up.railway.app',
    'https://*.railway.app',
    'https://*.up.railway.app',
    'https://kbytexfrontend.vercel.app',
    'https://*.vercel.app',

     'https://kbytex.com',
    'https://www.kbytex.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
        'rest_framework_simplejwt.token_blacklist',  # ADD THIS

    'corsheaders',
    'django_filters',
    
    # Local apps
    'api',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studypilot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studypilot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py - Force SQLite locally
import os
from pathlib import Path

# Get DATABASE_URL from environment
# === DATABASE CONFIGURATION - SIMPLIFIED ===
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    print("🚀 Connecting to Neon PostgreSQL...")
    
    # Clean up the URL
    if DATABASE_URL.startswith('postgres://'):
        DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
    
    # Remove channel_binding parameter as it's not needed
    if 'channel_binding=require' in DATABASE_URL:
        DATABASE_URL = DATABASE_URL.replace('&channel_binding=require', '')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'verceldb',
            'USER': 'default',
            'PASSWORD': 'AZ1s4miXNlPB',
            'HOST': 'ep-hidden-base-a40cjxlz.us-east-1.aws.neon.tech',
            'PORT': 5432,
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': 0,  # Important for Neon
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# For production, Railway will override this with DATABASE_URL
# Don't try to connect to Supabase locally
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# TEMPORARY: Simplify password validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,  # Reduced for testing
        }
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# === CORS SETTINGS ===
CORS_ALLOWED_ORIGINS = [
    'https://hadsxk-production.up.railway.app',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://kbytexfrontend.vercel.app',

    # ✅ Add your custom domain
    'https://kbytex.com',
    'https://www.kbytex.com',
]



CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
IS_RAILWAY = os.environ.get('RAILWAY_ENVIRONMENT') is not None or os.environ.get('RAILWAY_STATIC_URL') is not None

if IS_RAILWAY:
    print("🚀 Running on Railway - enabling production settings")
    DEBUG = False  # Force DEBUG=False on Railway
    # Enable WhiteNoise for static files
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    print("💻 Running locally - using development settings")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # CHANGE THIS LINE!
    ],
}

# === JWT SETTINGS ===
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=3),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,  # Change to True
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}


# === API KEYS & EXTERNAL SERVICES ===
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
 # === API KEYS & EXTERNAL SERVICES ===
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Image Generation APIs
REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN", "")
 
# Fallback keys for system use
GROQ_FALLBACK_KEY = os.getenv("GROQ_FALLBACK_KEY", "")
OPENAI_FALLBACK_KEY = os.getenv("OPENAI_FALLBACK_KEY", "")

# You may also want to add:
STABILITY_API_KEY = os.getenv("STABILITY_API_KEY", "")  # For Stability AI
DALL_E_API_KEY = os.getenv("DALL_E_API_KEY", "")  # For DALL-E if you want to add it later
# === REDIS CONFIGURATION ===
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Django Redis Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
        "KEY_PREFIX": "studypilot"
    }
}

# Optional: Use Redis for session storage
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# Optional: Use Redis for message queue (Celery)
# CELERY_BROKER_URL = REDIS_URL
# CELERY_RESULT_BACKEND = REDIS_URL


# === RATE LIMITING SETTINGS ===
# Free tier limits
FREE_TIER_DAILY_LIMIT = 50
FREE_TIER_MINUTE_LIMIT = 5

# Premium tier limits (for future)
PREMIUM_TIER_DAILY_LIMIT = 1000
PREMIUM_TIER_MINUTE_LIMIT = 30

# Unlimited tier limits (for future)
UNLIMITED_TIER_DAILY_LIMIT = 5000
UNLIMITED_TIER_MINUTE_LIMIT = 100


# === LOGGING ===
LOGGING_DIR = BASE_DIR / 'logs'
LOGGING_DIR.mkdir(exist_ok=True)  # Create directory if it doesn't exist

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGGING_DIR / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}


# === SECURITY SETTINGS (for production) ===
# Disable DRF static files in production
if not DEBUG:
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
        'DEFAULT_RENDERER_CLASSES': (
            'rest_framework.renderers.JSONRenderer',  # Only JSON in production
        ),
    }
else:
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
    }
    
    
    